title: Yoda's House
email: epalazzo@fra.utn.edu.ar
description: >-
  Very good my site is!
baseurl: /F2
url: https://frautn.github.io/
github_username:  frautn

# Build settings
theme: minima
plugins:
  - jekyll-feed
